FROM node:20
WORKDIR /app

# Needed by some npm packages on alpine
# RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .


ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]