FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps
# RUN npm ci --legacy-peer-deps --only=production

COPY . .

# Build Next.js
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]