#import "../../_fragment/error.graphql"

fragment VouchersInfo on Vouchers {
  _id
  title
  code
  description

  type
  status

  value
  maxDiscount
  minSpend

  appliesTo {
    scope
    _ids_product
    categoryIds
    _ids_store
  }
  excludes {
    _ids_product
    categoryIds
    _ids_store
  }
  combinable

  bogo {
    buyQty
    getQty
    free_ids_product
  }
  tiered {
    minSpend
    discountValue
    type
  }

  startDate
  endDate
  usageLimit
  perCustomerLimit

  usedCount
  usage {
    _id_user
    count
    lastUsedAt
  }

  error {...ErrorInfo}
}
