#import "../_fragment/error.graphql"
#import "../_fragment/success.graphql"

mutation CompleteOrderVerification(
  $_id_order: ID!
  $delivery_basket_ids: [ID!]!
  $notes: String
) {
  completeOrderVerification(
    _id_order: $_id_order
    delivery_basket_ids: $delivery_basket_ids
    notes: $notes
  ) {
    order {
      _id
      serial
      current_stage
      locked_by
    }
    session {
      _id
      performance {
        total_units_processed
        successful_units
      }
    }
    success {
      ...SuccessInfo
    }
    error {
      ...ErrorInfo
    }
  }
}