query GetMyLockedOrders {
  getMyLockedOrders {
    _id
    serial
    store { _id title }
  }
}


# query GetMyLockedOrders {
#   getMyLockedOrders {
#     orders {
#       _id
#       serial
#       customer {
#         _id
#         name
#         email
#         phone  # Resolved from user profile via resolver
#       }
#       current_order {
#         ...ProcessingDataInfo
#       }
#       processing_stages {
#         picking {
#           handled_by {
#             _id
#             name
#           }
#           created_at
#           updated_at
#         }
#       }
#       current_stage
#       status {
#         order
#         payment
#         fulfillment
#       }
#       locked_by
#       locked_at
#       lock_expires_at
#       createdAt
#     }
#     total
#     error {
#       ...ErrorInfo
#     }
#   }
# }
