#import "../_fragment/error.graphql"
#import "../_fragment/success.graphql"
#import "../order/_fragment/OrderItems.graphql"

mutation MarkOrderItemMissing(
  $_id_order: ID!
  $_id_product: ID!
  $reason: String!
) {
  markOrderItemMissing(
    _id_order: $_id_order
    _id_product: $_id_product
    reason: $reason
  ) {
    order {
      _id
      current_order {
        items {
          ...OrderItemsInfo
        }
      }
    }
    success {
      ...SuccessInfo
    }
    error {
      ...ErrorInfo
    }
  }
}