#import "../_fragment/error.graphql"
#import "../_fragment/success.graphql"
#import "../order/_fragment/OrderItems.graphql"

mutation MarkOrderItemMismatch(
  $_id_order: ID!
  $_id_product: ID!
  $qty_verified: Int!
  $reason: String!
) {
  markOrderItemMismatch(
    _id_order: $_id_order
    _id_product: $_id_product
    qty_verified: $qty_verified
    reason: $reason
  ) {
    order {
      _id
      current_order {
        items {
          ...OrderItemsInfo
        }
      }
    }
    success {
      ...SuccessInfo
    }
    error {
      ...ErrorInfo
    }
  }
}