#import "../_fragment/error.graphql"
#import "../_fragment/success.graphql"

mutation RemoveOrderFromTillSession(
  $_id_order: ID!
  $reason: String
) {
  removeOrderFromTillSession(
    _id_order: $_id_order
    reason: $reason
  ) {
    session {
      _id
      till_verification_orders {
        _id_order
        order_serial
        order_status
      }
      performance {
        total_units_processed
        successful_units
      }
    }
    success {
      ...SuccessInfo
    }
    error {
      ...ErrorInfo
    }
  }
}
