// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import '@ant-design/v5-patch-for-react-19';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

import "@/styles/global.scss";
import ApolloWrapper from "@/aClient/provider";
// import Nav from "@/components/nav";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ReduxProvider from '@/rStore/provider';
import { SessionProvider } from "@_/lib/auth/SessionProvider";
import ValidateClientSession from '@/lib/auth/validateClientSession';
import { Header } from "@/template";
import NextTopLoader from 'nextjs-toploader';
import { Footer } from '@_/template/footer';



export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          {/* <SessionProvider> */}
            <AntdRegistry>
              <ReduxProvider>
                <ValidateClientSession>
                  <Header />
                  <NextTopLoader />
                  {children}
                  <Footer />
                </ValidateClientSession>
              </ReduxProvider>
            </AntdRegistry>
          {/* </SessionProvider> */}
        </ApolloWrapper>
      </body>
    </html>
  );
}


