#import "../_fragment/paginationResults.graphql"
#import "../_fragment/error.graphql"

query appPagesQuery($limit: Int, $page: Int, $filter: String, $others:String) {
    appPagesQuery(limit: $limit, page: $page, filter: $filter, others: $others) {
        pagination { ...PaginationResultsInfo }
        edges {
            _id
            # _id_parent: ID
            title
            slug
            deleteable
            published
            description
            page_type { title type }
            # createdAt

            created_by { name }
            last_updated_by { name }

            scheduled_from
            scheduled_to

            updatedAt
        }
        error { ...ErrorInfo }
    }
}