#import "../_fragment/paginationResults.graphql"
#import "../_fragment/error.graphql"

query productsQuery($limit: Int, $page: Int, $filter: String, $others: String, $_id_store: ID) {
    productsQuery(limit: $limit, page: $page, filter: $filter, others: $others, _id_store: $_id_store) {
        pagination { ...PaginationResultsInfo }
        edges { 
            # ...ProductInfo
            _id
            _id_parent
            title
            categories { _id title }
            variations_count
            barcode
            # attributes {...Prod_AttributesSchemaReff_Info}
            status
            temp_sensitivity
            unfit_for_dispatch
            picture { thumbnails }

            store {
                # _id
                # store_title
                store_status
                # store_code
                price_was
                price
                status
                available_qty
                # reserved_qty
            }

            # variations { 
            #     _id
            #     _id_parent
            #     title
            # }

            error { ...ErrorInfo } 
        }
        error { ...ErrorInfo }
    }
}
