#import "../../_fragment/error.graphql"
#import "../../_fragment/GeoPointReff.graphql"
#import "../../_fragment/GeoZoneReff.graphql"

# fragment GeoZoneReffInfo  on GeoZoneReff {
#     # _id_zone
#     # title
#     # category
#     city {
#       _id
#       title
#       code
#       child_of
#       center {...GeoPointReffInfo}
#       type
#       status
#     }
#     # status
# }

fragment VehiclesInfo on Vehicles {
  _id
  title
  registration_no
  zones { 
    ...GeoZoneReffInfo
    city {
      _id
      title
      code
      child_of
      center {...GeoPointReffInfo}
      type
      status
    }
  }
  status
  drivers { _id name }
  store {
    _id title code
    center {...GeoPointReffInfo}
  }
  box_cpacity

  # createdAt
  # updatedAt
  error {...ErrorInfo}
}