
#import "./_fragment/OrderDeliverySlot.graphql"
#import "./_fragment/OrderPayment.graphql"
#import "./_fragment/OriginalOrder.graphql"

#import "../_fragment/UserAddressesRef.graphql"
#import "../_fragment/error.graphql"
#import "../_fragment/GeoZoneReff.graphql"

query getOrignalOrder($filter: String!) {
    order(filter: $filter) {
        _id
        serial
        store { _id title }
        zone { ...GeoZoneReffInfo }
        customer { _id name }

        original_order { ...OriginalOrderInfo }

        current_order {
            baskets { _id title barcode color }
            handled_by { _id name }
            notes
            _id_session
        }

        processing_stages {
            till_verification {
                baskets { _id title barcode color }
                handled_by { _id name }
            }
            delivery {
                baskets { _id title barcode color }
                handled_by { _id name }
            }
        }

        delivery_slot { ...OrderDeliverySlotInfo }
        delivery_note

        # viewed
        status { order payment fulfillment }
        current_stage
        payment { ...OrderPaymentInfo }

        sub_status {
            code
            updated_at
            updated_by { _id name }
            eta_minutes
            distance_meters
        }

        activity_logs {
            _id
            action
            message
            at
            by { _id name email }
            meta
            location {
                type
                coordinates
            }
        }

        shippingAddress { ...UserAddressesRefInfo }

        pickup_allow

        locked_by
        locked_at
        lock_expires_at
        lock_type

        customer_feedback

        createdAt
        updatedAt

        error { ...ErrorInfo }
        success { message details code  }
        warning { code message details } 
    }
}
