#import "../_fragment/paginationResults.graphql"
#import "../_fragment/error.graphql"

#import "./_fragment/OrderTotals.graphql"
#import "./_fragment/OrderDeliverySlot.graphql"


query ordersQuery($limit: Int, $page: Int, $filter: String, $others: String, $_id_store: ID, $filterGroups: [DynamicFilterGroupInput!], $searchTerm: String) {
    ordersQuery(limit: $limit, page: $page, filter: $filter, others: $others, _id_store: $_id_store, filterGroups: $filterGroups, searchTerm: $searchTerm) {
        pagination { ...PaginationResultsInfo }
        edges { 
            _id
            serial
            barcode: serial
            store { _id title }
            zone {
                _id_zone
                title
                # category
                # polygon: GeoPolygonReff
                # city: LocationsReff
                # status
                # order_limit: Int # for delivery slots
            }
            customer { _id name }

            original_order {
                totals { ...OrderTotalsInfo }
            }

            # current_order: ProcessingData
            current_order {
                baskets { _id title barcode color }
                totals { ...OrderTotalsInfo }
            }
            processing_stages {
                picking {
                    baskets { _id title barcode color }
                    handled_by { _id name }
                }
                till_verification { baskets { _id title barcode color } }
            }

            delivery_slot { ...OrderDeliverySlotInfo }
            # delivery_note: String

            viewed
            status { order payment fulfillment }
            current_stage

            # payment: OrderPayment

            # shippingAddress: UserAddressesRef
            # billingAddress: UserAddressesRef

            pickup_allow

            locked_by
            # locked_at
            # lock_expires_at
            lock_type

            createdAt
            updatedAt

            # error: Error 
        }
        error { ...ErrorInfo }
    }
}
