#import "../_fragment/error.graphql"
#import "../_fragment/success.graphql"

mutation clearDriverOrderCollectionBulk(
  $_id_session: ID
  $_id_driver: ID
  $items: [ClearDriverOrderItemInput!]!
) {
  clearDriverOrderCollectionBulk(
    _id_session: $_id_session
    _id_driver: $_id_driver
    items: $items
  ) {
    cleared_count
    recorded_count
    session {
      _id
      driver_wallet {
        total_cod_collected
        deposited_amount
        pending_deposit
        is_settled
      }
      all_baskets_returned
    }
    success { ...SuccessInfo }
    error { ...ErrorInfo }
  }
}
