#import "../_fragment/error.graphql"
#import "../_fragment/UserReff.graphql"

query getDriverOrders($_id_driver: ID!, $_id_session: ID) {
  getDriverOrders(_id_driver: $_id_driver, _id_session: $_id_session) {
    session {
      _id
      session_started_at
      driver_wallet {
        total_cod_collected
        deposited_amount
        pending_deposit
        is_settled
      }
      baskets_assigned
      baskets_returned
      all_baskets_returned
    }
    session_missing
    orders {
      _id
      serial
      customer { ...UserReffInfo }
      current_stage
      is_cod
      amount_collected
      amount_deposited
      amount_remaining
      cod_deposited
      baskets_count
      baskets_received
      pending_clearance
      baskets {
        _id
        title
        barcode
        color
      }
    }
    error { ...ErrorInfo }
  }
}
